import { Archivo } from "next/font/google";
import "./globals.css";


import Header from "@/components/Header";
const arChivo = Archivo({
  subsets: ["latin"], // pastikan ini adalah subset yang valid
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-archivo'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={arChivo.variable}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
